name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache dependencies and build outputs
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install library dependencies
        run: pio pkg install

      - name: Build PlatformIO Project
        run: pio run

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
            name: firmware
            include-hidden-files: true
            path: .pio/build/*/*.bin

      - name: Convert bin to uf2
        run: |
          mkdir uf2
          cd uf2
          cp ../.pio/build/*/firmware.bin ./
          ls -al
          wget https://raw.githubusercontent.com/Microsoft/uf2/refs/heads/master/utils/uf2conv.py https://raw.githubusercontent.com/Microsoft/uf2/refs/heads/master/utils/uf2families.json
          python uf2conv.py firmware.bin -c -b 0x00 -f ESP32S3
          ls -al

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
            name: firmware.uf2
            path: ./*.uf2
